config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  root 'vets#index'
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products
      #resources :vets do
      #  resources :appointments
      #end
      #resources :pets do
      #  resources :appointments
      #end

      #resources :appointments
      # could also combine this in
      resources :vets, :pets do
	resources :appointments, shallow: true
      end

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :vet
  belongs_to :pet

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  has_many :appointments
  has_many :vets, through: :appointments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/models/vet.rb
class Vet < ActiveRecord::Base
  has_many :appointments
  has_many :pets, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def new
  end

  def create
    @vet = Vet.find(params[:vet_id])
    @appointment = @vet.appointments.create!(appointment_params)
    # consider adding a user_id to appointment table so you can know who created an appointment

    redirect_to @vet
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  # in the future, consider adding edit / delete functionality as well
  # def destroy
  #   Appointment.find(params[:id]).destroy
  # end
  # also check out http://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-dependent
  # as a bonus, restrict update/destroy to the person who created the appointment

  private
  def appointment_params
    params.require(:appointment).permit(:appointmenttime, :pet_id)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  before_action :set_pets, only: [:index, :new, :show, :create, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :show, :create, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.create!(pet_params)

    if @pet.save
      redirect_to @pet
    else
      render 'new'
    end
  end

  def edit
    @pet =Pet.find(params[:id])
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      flash[:notice] = "#{@pet.name} was successfully updated."
      redirect_to @pet
    else
      render :edit
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy

    @pets = Pet.all
    redirect_to pets_path
  end


private
  def pet_params
    params.require(:pet).permit(:name, :breed, :gender, :dob)
  end

  def set_pets
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create!(user_params)

  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "#{@user.name} was successfully updated."
      redirect_to @user
    else
      render :edit
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy

    @user = User.all
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end


end

app/controllers/vets_controller.rb
class VetsController < ApplicationController

  before_action :set_vets, only: [:index, :new, :show, :create, :edit, :update, :destroy]
  # the only is uneccesarry if you want this action to happen on every route
  # check out http://guides.rubyonrails.org/action_controller_overview.html#filters
  before_action :authenticate_user!, only: [:index, :new, :show, :create, :edit, :update, :destroy]

  def index
    @vets = Vet.all
  end

  def new
    @vet = Vet.new
  end

  def edit
    @vet = Vet.find(params[:id])
  end

  def create
    @vet = Vet.create!(vet_params)
    # if you add user_id to vet table, you can:
    # @vet = Vet.create!(vet_params.merge(user: current_user))

    if @vet.save
      redirect_to @vet
    else
      render 'new'
    end
  end

  def show
    @vet = Vet.find(params[:id])
    @pet = Pet.find_by(params[:pet_id])
    @appointment = Appointment.new
  end

  def update
    @vet = Vet.find(params[:id])
    if @vet.update(vet_params)
      flash[:notice] = "#{@vet.name} was successfully updated."
      redirect_to @vet
    else
      render :edit
    end
  end

  def destroy
    @vet = Vet.find(params[:id])
    @vet.destroy

    redirect_to vets_path
  end

private
  def vet_params
    params.require(:vet).permit(:name, :school)
  end

  def appointment_params
    params.require(:appointment).permit(:appointmenttime, :pet_id, :vet_id)
  end

  def set_vets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vet Scheduler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <header>
    <h1>Doctor Doolittle's Veterinary Medicine</h1>
  </header>

    <% if current_user %>
      <h3><%= link_to 'Sign Out', destroy_user_session_path, class: 'btn btn-default', :method => :delete %></h3>
    <% else %>
      <h3><%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-default' %> or <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-default' %></h3>
    <% end %>

    <h4><%= link_to 'Our Vets', vets_path %> | <%= link_to 'Our Pets', pets_path %></h4>

  <%= yield %>
  </div>
</body>
</html>

app/views/pets/_form.html.erb
<%= form_for @pet do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :breed %>
    <%= f.text_field :breed %>
  </p>
  <p>
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </p>
  <p>
    <%= f.label :dob %>
    <%= f.text_field :dob %>
  </p>

  <%= f.submit %>

<% end %>

app/views/pets/edit.html.erb
<h2>Edit Pet Info</h2>

<%= render 'form' %>

app/views/pets/index.html.erb
<h2>Pets We Care For</h2>
<h3><%= link_to 'Add a new pet', new_pet_path, class: 'btn btn-default' %></h3>

<ul>
  <% @pets.each do |pet| %>
    <li>
      <a href="/pets/<%= pet.id %>">
        <%= pet.name %>
      </a>
    </li>
  <% end %>
</ul>

app/views/pets/new.html.erb
<h4>Add a new pet</h4>

<%= render 'form' %>

app/views/pets/show.html.erb
<h2>Pet Info</h2>

<p>
<strong>Name:</strong>
<%= @pet.name %>
</p>

<p>
<strong>Breed:</strong>
<%= @pet.breed %>
</p>

<p>
<strong>Gender</strong>:
<%= @pet.gender %>
</p>

<p>
<strong>DOB:
</strong><%= @pet.dob %>
<!-- storing `dob` as a datetime object as well will allow you to format the date
differently in the future. -->
</p>

<%= link_to 'back to pet list', pets_path %> | <%= link_to 'edit', edit_pet_path %> | <%= link_to 'delete', pet_path(@pet), method: :delete, class: 'delete' %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  
  <%= f.submit %>

<% end %>

app/views/users/index.html.erb
<h2>Vets in Our Practice</h2>

<h3><%= link_to 'Add a new vet', new_user_path %></h3>

<ul>
  <% @users.each do |user| %>
    <li>
      <a href="/users/<%= user.id %>">
        <%= user.email %>
      </a>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h2>Vet Info</h2>

<p>
<strong>Name:</strong>
<%= @user.name %>
</p>

<p>
<strong>Email:</strong>
<%= @user.email %>
</p>


<%= link_to 'back to vets', users_path %> | <%= link_to 'edit', edit_user_path %> | <%= link_to 'delete', user_path(@user), method: :delete, class: 'delete' %>

app/views/vets/_form.html.erb
<%= form_for @vet do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :school %>
    <%= f.text_field :school %>
  </p>

  <%= f.submit %>

<% end %>

app/views/vets/edit.html.erb
<h4>Edit Vet Info</h4>

<%= render 'form' %>

app/views/vets/index.html.erb
<h2>Our Vets</h2>

<%= link_to 'Add a new vet', new_vet_path, class: 'btn btn-default' %>


<ul>
  <% @vets.each do |vet| %>
    <li>
      <h4><a href="/vets/<%= vet.id %>">
        <%= vet.name %>
      </a></h4>
    </li>
  <% end %>
</ul>

app/views/vets/new.html.erb
<h4>Add a new vet</h4>

<%= render 'form' %>

app/views/vets/show.html.erb
<h2>Vet Info</h2>

<p>
<strong>Name:</strong>
<%= @vet.name %>
</p>

<p>
<strong>School:</strong>
<%= @vet.school %>
</p>


<%= link_to 'back to vets', vets_path %> | <%= link_to 'edit', edit_vet_path %> | <%= link_to 'delete', vet_path(@vet), method: :delete, class: 'delete' %>

<h3>Upcoming Appointments</h3>

<% if !@vet.appointments.empty? %>
  <ul>
    <% @vet.appointments.each do |appointment| %>
      <li>
        <%= "#{appointment.pet.name} (#{appointment.appointmenttime})" %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No appointments scheduled.</p>
<% end %>

<h4>Add an Appointment</h4>

<%= form_for [@vet, @appointment] do |f| %>

  <div class="form-group">
    <%= f.label :critter %>
    <%= f.collection_select :pet_id, Pet.order(:name), :id, :name, include_blank: true %>
    <!-- can also set default ordering by using scope - http://api.rubyonrails.org/classes/ActiveRecord/Scoping/Named/ClassMethods.html -->
  </div>
  <div class="form-group">
    <%= f.label :appointment %>
    <%= f.text_field :appointmenttime %>
    <!-- check out http://guides.rubyonrails.org/form_helpers.html#using-date-and-time-form-helpers -->
  </div>

  <%= f.submit %>
<% end %>